Bili@DESKTOP-6B9N5IR MINGW64 ~ $ cd alx-zero_day
Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ cd git checkout -b update_script
bash: cd: too many arguments

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git update_script
git: 'update_script' is not a git command. See 'git --help'.

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git checkout
Your branch is up to date with 'origin/main'.

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git checkout update_script
error: pathspec 'update_script' did not match any file(s) known to git

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git branch update_script

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git checkout
Your branch is up to date with 'origin/main'.

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ cd update_script
bash: cd: update_script: No such file or directory

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git branch --list
* main
  update_script

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (main)
$ git checkout update_script
Switched to branch 'update_script'

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (update_script)
$ ls
0x03-git/  README.md

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day (update_script)
$ cd 0x03-git

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day/0x03-git (update_script)
$ ls
README.md  bash/  c/  js/

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day/0x03-git (update_script)
$ cd bash

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day/0x03-git/bash (update_script)
$ touch 98

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day/0x03-git/bash (update_script)
$ vi alx

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day/0x03-git/bash (update_script)
$ vi school

Bili@DESKTOP-6B9N5IR MINGW64 ~/alx-zero_day
clear

cd ..

wq
x